### PR TITLE
Fix cache hit in CodeAnalysisRuleSetPredictor

### LINKED ISSUE #136: File cache in CodeAnalysisRuleSetPredictor does not consider the rule set directories
The cache hit is based on file path

https://github.com/microsoft/MSBuildPrediction/blob/f852f0391be0cb2d970a04e7d84ee04c59e40bbb/src/BuildPrediction/Predictors/CodeAnalysisRuleSetPredictor.cs#L151

however some projects may load the same ruleset file with different value of `CodeAnalysisRuleSetDirectories`. In case a ruleset file with includes and empty `CodeAnalysisRuleSetDirectories` is parsed (and cached), the included will be omitted. Subsequent parsing of the same ruleset file, will yield the same, small set of inputs, despite the fact that they may provide more directories in `CodeAnalysisRuleSetDirectories`.

### PR DESCRIPTION
**Pull request by stan-sz**
Fixes #136

### CODE REVIEW

File: src/BuildPrediction/Predictors/CodeAnalysisRuleSetPredictor.cs [hunk 1]
```diff
@@ -252,5 +254,63 @@ private HashSet<string> ParseRuleset(
                 return _emptySet;
             }
         }
+
+        private sealed record RuleSetCacheKey
```
Comment (dfederm) [inline src/BuildPrediction/Predictors/CodeAnalysisRuleSetPredictor.cs]: Use a record struct?

File: src/BuildPrediction/Predictors/CodeAnalysisRuleSetPredictor.cs [hunk 2]
```diff
@@ -252,5 +254,63 @@ private HashSet<string> ParseRuleset(
...
+        {
+            public RuleSetCacheKey(string ruleSetPath, IReadOnlyList<string> ruleSetDirectories)
+            {
+                RuleSetPath = ruleSetPath;
+                RuleSetDirectories = ruleSetDirectories.Count == 0
+                    ? []
+                    : ruleSetDirectories.ToImmutableArray();
```
Comment (dfederm) [inline src/BuildPrediction/Predictors/CodeAnalysisRuleSetPredictor.cs]: `ToImmutableArray` are pretty heavy. You should just use a `List<string>` since that's the input

File: src/BuildPrediction/Predictors/CodeAnalysisRuleSetPredictor.cs [hunk 3]
```diff
@@ -252,5 +254,63 @@ private HashSet<string> ParseRuleset(
...
+            }
+
+            public string RuleSetPath { get; }
+
+            public IReadOnlyList<string> RuleSetDirectories { get; }
```
Comment (dfederm) [inline src/BuildPrediction/Predictors/CodeAnalysisRuleSetPredictor.cs]: `List<string>` to avoid `callvirt`

File: src/BuildPrediction/Predictors/CodeAnalysisRuleSetPredictor.cs [hunk 4]
```diff
@@ -252,5 +254,63 @@ private HashSet<string> ParseRuleset(
                 return _emptySet;
             }
         }
+
+        private sealed record RuleSetCacheKey
+        {
+            public RuleSetCacheKey(string ruleSetPath, IReadOnlyList<string> ruleSetDirectories)
```
Comment (dfederm) [inline src/BuildPrediction/Predictors/CodeAnalysisRuleSetPredictor.cs]: Primary ctor?

File: src/BuildPrediction/Predictors/CodeAnalysisRuleSetPredictor.cs [hunk 5]
```diff
@@ -252,5 +254,63 @@ private HashSet<string> ParseRuleset(
...
+                        return false;
+                    }
+                }
+
+                return true;
+            }
+
+            public override int GetHashCode()
+            {
+                int hash = PathComparer.Instance.GetHashCode(RuleSetPath);
```
Comment (dfederm) [inline src/BuildPrediction/Predictors/CodeAnalysisRuleSetPredictor.cs:294]: Is `HashCode` part of the BCL we're targeting?

File: src/BuildPrediction/Predictors/CodeAnalysisRuleSetPredictor.cs (hunk 4 above)
Comment (stan-sz) [reply src/BuildPrediction/Predictors/CodeAnalysisRuleSetPredictor.cs]: Won't work due to https://stackoverflow.com/questions/62648189/testing-c-sharp-9-0-in-vs2019-cs0518-isexternalinit-is-not-defined-or-imported

File: src/BuildPrediction/Predictors/CodeAnalysisRuleSetPredictor.cs (hunk 5 above)
Comment (stan-sz) [reply src/BuildPrediction/Predictors/CodeAnalysisRuleSetPredictor.cs:294]: Not available in net472, but can use the nuget package.

File: src/BuildPrediction/Predictors/CodeAnalysisRuleSetPredictor.cs [hunk 6]
```diff
@@ -252,5 +253,53 @@ private HashSet<string> ParseRuleset(
                 return _emptySet;
             }
         }
+
+        private readonly record struct RuleSetCacheKey
+        {
+            public RuleSetCacheKey(string ruleSetPath, IReadOnlyList<string> ruleSetDirectories)
+            {
+                RuleSetPath = ruleSetPath;
+                RuleSetDirectories = new List<string>(ruleSetDirectories);
```
Comment (dfederm) [inline src/BuildPrediction/Predictors/CodeAnalysisRuleSetPredictor.cs]: This allocation should be avoided

Comment (dfederm) [reply src/BuildPrediction/Predictors/CodeAnalysisRuleSetPredictor.cs]: Just change the arg to a `List` and do a direct assignment.

Comment (stan-sz) [reply src/BuildPrediction/Predictors/CodeAnalysisRuleSetPredictor.cs]: Done

**Review by dfederm — APPROVED** [review]
